# Camera intrinsic matrix parameters (OpenCV)

home_directory: "/home/arrow"

camera:
  #fx: 544.771755
  #fy: 546.966312
  #cx: 322.376103
  #cy: 245.357925

  # The values below assume a perfect case in simulation/gazebo for the camera specifications in
  # depth_camera_new.sdf, check https://bitbucket.org/osrf/sdformat/pull-requests/248/added-camera-intrinsics-fx-fy-cx-cy-s/activity
  fx: 554.0
  fy: 554.0
  cx: 320.0
  cy: 240.0

  width: 640
  height: 480

semantic_pcl:
  color_image_topic: "/camera/rgb/image_raw"
  #depth_image_topic: "/camera/depth_registered/image_raw"
  depth_image_topic: "/camera/depth/image_raw"
  frame_id: "camera_link"
  dataset: "kucarsRisk" 
  model_path: "/home/arrow/catkin_ws/src/semantic_hazard_cloud/models_trained/path_to_checkpoints_model.h5"
  model_json_path: "/home/arrow/catkin_ws/src/semantic_hazard_cloud/models_trained/path_to_checkpoints_config.json"
  checkpoints_path: "/home/arrow/catkin_ws/src/semantic_hazard_cloud/models_trained/"
  throttle_rate: 0.5 # 1/val in hz 
  real_sense: false

model_params:
  test_image_path_input: "/home/arrow/catkin_ws/src/semantic_hazard_cloud/test_images/frame0020.jpg"
  test_image_path_output: "/home/arrow/catkin_ws/src/semantic_hazard_cloud/test_images/outFrame0020.png"
  test_image_path_output_folder: "/home/arrow/catkin_ws/src/semantic_hazard_cloud/test_images_folder/"
  model_input_height: 480
  model_input_width: 640
  model_output_height: 240
  model_output_width: 320
  model_n_classes: 7
  model_checkpoints_path:  "/home/arrow/catkin_ws/src/semantic_hazard_cloud/models_trained/path_to_checkpoints"
